services:
  # Backend API
  - type: web
    name: pos-api
    runtime: docker
    dockerfilePath: ./POS/POS.Api/Dockerfile
    dockerContext: ./POS/POS.Api
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDb__ConnectionString
        value: mongodb+srv://taariqhendricksh1_db_user:EKI7A7WDCPtVgxYk@clusterpos.zyrhmrz.mongodb.net/?appName=ClusterPos
      - key: MongoDb__DatabaseName
        value: pos_db
      - key: Email__SmtpServer
        value: smtp.gmail.com
      - key: Email__SmtpPort
        value: "587"
      - key: Email__SenderEmail
        sync: false
      - key: Email__SenderName
        value: POS Store
      - key: Email__Password
        sync: false
      - key: Email__UseSsl
        value: "true"
      - key: App__CompanyName
        value: My POS Store
      - key: App__DefaultTaxRate
        value: "15"
      - key: App__CurrencySymbol
        value: R
      - key: App__InvoicePrefix
        value: INV
    healthCheckPath: /api/products/shops

  # Frontend
  - type: web
    name: pos-frontend
    runtime: docker
    dockerfilePath: ./POS/pos-frontend/Dockerfile
    dockerContext: ./POS/pos-frontend
    plan: free
    envVars:
      - key: API_URL
        value: https://pos-api.onrender.com
