services:
  # Backend API
  api:
    build:
      context: ./POS.Api
      dockerfile: Dockerfile
    container_name: pos-api
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDb__ConnectionString=mongodb+srv://taariqhendricksh1_db_user:EKI7A7WDCPtVgxYk@clusterpos.zyrhmrz.mongodb.net/?appName=ClusterPos
      - MongoDb__DatabaseName=pos_db
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./pos-frontend
      dockerfile: Dockerfile
    container_name: pos-frontend
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    restart: unless-stopped
